src/Entity/NameBasics.php
<?php

namespace App\Entity;

use App\Repository\NameBasicsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NameBasicsRepository::class)
 */
class NameBasics
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $primaryName;

    /**
     * @ORM\Column(type="integer")
     */
    private $birthYear;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $deathYear;

    /**
     * @ORM\ManyToMany(targetEntity=TitleBasic::class, inversedBy="Acteurs")
     */
    private $knownForTitles;

    /**
     * @ORM\Column(type="json")
     */
    private $primaryProfession = [];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    public function __construct()
    {
        $this->knownForTitles = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrimaryName(): ?string
    {
        return $this->primaryName;
    }

    public function setPrimaryName(string $primaryName): self
    {
        $this->primaryName = $primaryName;

        return $this;
    }

    public function getBirthYear(): ?int
    {
        return $this->birthYear;
    }

    public function setBirthYear(int $birthYear): self
    {
        $this->birthYear = $birthYear;

        return $this;
    }

    public function getDeathYear(): ?int
    {
        return $this->deathYear;
    }

    public function setDeathYear(?int $deathYear): self
    {
        $this->deathYear = $deathYear;

        return $this;
    }


    /**
     * @return Collection<int, TitleBasic>
     */
    public function getKnownForTitles(): Collection
    {
        return $this->knownForTitles;
    }

    public function addKnownForTitle(TitleBasic $knownForTitle): self
    {
        if (!$this->knownForTitles->contains($knownForTitle)) {
            $this->knownForTitles[] = $knownForTitle;
        }

        return $this;
    }

    public function removeKnownForTitle(TitleBasic $knownForTitle): self
    {
        $this->knownForTitles->removeElement($knownForTitle);

        return $this;
    }

    public function getPrimaryProfession(): ?array
    {
        return $this->primaryProfession;
    }

    public function setPrimaryProfession(array $primaryProfession): self
    {
        $this->primaryProfession = $primaryProfession;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }


}

src/Entity/TitleBasic.php
<?php

namespace App\Entity;

use App\Repository\TitleBasicRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TitleBasicRepository::class)
 */
class TitleBasic
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titleType;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $primaryTitle;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $originalTitle;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isAdult;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $startYear;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $endYear;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $runtimeMinutes;

    /**
     * @ORM\Column(type="json")
     */
    private $Genres = [];

    /**
     * @ORM\ManyToMany(targetEntity=NameBasics::class, mappedBy="knownForTitles")
     */
    private $Acteurs;

    /**
     * @ORM\OneToOne(targetEntity=TitleCrew::class, mappedBy="Title", cascade={"persist", "remove"})
     */
    private $crew;

    public function __construct()
    {
        $this->Acteurs = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitleType(): ?string
    {
        return $this->titleType;
    }

    public function setTitleType(string $titleType): self
    {
        $this->titleType = $titleType;

        return $this;
    }

    public function getPrimaryTitle(): ?string
    {
        return $this->primaryTitle;
    }

    public function setPrimaryTitle(?string $primaryTitle): self
    {
        $this->primaryTitle = $primaryTitle;

        return $this;
    }

    public function getOriginalTitle(): ?string
    {
        return $this->originalTitle;
    }

    public function setOriginalTitle(?string $originalTitle): self
    {
        $this->originalTitle = $originalTitle;

        return $this;
    }

    public function isIsAdult(): ?bool
    {
        return $this->isAdult;
    }

    public function setIsAdult(bool $isAdult): self
    {
        $this->isAdult = $isAdult;

        return $this;
    }

    public function getStartYear(): ?\DateTimeInterface
    {
        return $this->startYear;
    }

    public function setStartYear(\DateTimeInterface $startYear): self
    {
        $this->startYear = $startYear;

        return $this;
    }

    public function getEndYear(): ?\DateTimeInterface
    {
        return $this->endYear;
    }

    public function setEndYear(\DateTimeInterface $endYear): self
    {
        $this->endYear = $endYear;

        return $this;
    }

    public function getRuntimeMinutes(): ?int
    {
        return $this->runtimeMinutes;
    }

    public function setRuntimeMinutes(int $runtimeMinutes): self
    {
        $this->runtimeMinutes = $runtimeMinutes;

        return $this;
    }

    public function getGenres(): ?array
    {
        return $this->Genres;
    }

    public function setGenres(array $Genres): self
    {
        $this->Genres = $Genres;

        return $this;
    }

    /**
     * @return Collection<int, NameBasics>
     */
    public function getActeurs(): Collection
    {
        return $this->Acteurs;
    }

    public function addActeur(NameBasics $acteur): self
    {
        if (!$this->Acteurs->contains($acteur)) {
            $this->Acteurs[] = $acteur;
            $acteur->addKnownForTitle($this);
        }

        return $this;
    }

    public function removeActeur(NameBasics $acteur): self
    {
        if ($this->Acteurs->removeElement($acteur)) {
            $acteur->removeKnownForTitle($this);
        }

        return $this;
    }

    public function getCrew(): ?TitleCrew
    {
        return $this->crew;
    }

    public function setCrew(TitleCrew $crew): self
    {
        // set the owning side of the relation if necessary
        if ($crew->getTitle() !== $this) {
            $crew->setTitle($this);
        }

        $this->crew = $crew;

        return $this;
    }



}

templates/index/fiche.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ film.primaryTitle }}{% endblock %}

{% block body %}
    <h1>{{ film.primaryTitle }}</h1>
    {% if film.originalTitle != film.primaryTitle %}
    <h4>Titre Original : {{ film.originalTitle }}</h4>
    {% endif %}
    <h5>{{ film.titleType }}</h5><br>

    {% if film.titleType == 'série' %}

        <li>Début : {{ film.startYear|date('d-m-Y') }}</li>
        <li>Fin : {{ film.endYear|date('d-m-Y') }}</li>
    {% endif %}

    {% if film.titleType == 'Film' %}

        <li>
            Durée : {{ film.runtimeMinutes }} minutes
        </li>
    {% endif %}
    <li>
        Catégorie :
        {% if film.isAdult == "true" %}
            Adultes
        {% else %}
            Tout Public
        {% endif %}
    </li>

    <li>Genres :
        {% for genre in film.genres %}
            {{ genre }}
        {% endfor %}
    </li>

    <li>
        Directeurs :
        {% if film.crew|length==0 %}
            Non renseigné
        {% else %}
            {% for directeur in film.crew.directors %}
                {{ directeur.name }} {{ directeur.primaryName }}
            {% endfor %}
        {% endif %}
    </li>

    <li>
        Acteur(s) :{% if film.acteurs|length ==0 %} Non Renseigné
        {% else %}
        {% for acteur in film.acteurs %}
            <ol>
            {{ acteur.name }} {{ acteur.PrimaryName }}
            </ol>
        {% endfor %}
        {% endif %}
    </li>
{% endblock %}

templates/index/fichePersonne.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ personne.name }}{{ personne.primaryName }}{% endblock %}

{% block body %}
    <h1>{{ personne.name }} {{ personne.primaryName }}</h1>

        <li>Année de Naissance : {{ personne.birthYear }}</li>
    {%if personne.deathYear %}
        <li>Année de décès : {{ personne.deathYear }} à {{ personne.deathYear - personne.birthYear}} ans</li>
    {% endif %}

    <li>Métiers :
        {% for job in personne.primaryProfession %}
            {{ job }}
        {% endfor %}
    </li>

        {% if personne.knownForTitles|length ==0 %}
        {% else %}
            <li>
        Connu pour avoir joué dans :
        {% for titre in personne.knownForTitles %}
            <ol>
                {{ titre.primaryTitle }}
            </ol>
        {% endfor %}
            </li>
        {% endif %}

    {% if titres|length ==0 %}
    {% else %}
        <li>
            Connu pour avoir été le directeur de :
            {% for titre in titres %}
                <ol>
                    {{ titre.primaryTitle }}
                </ol>
            {% endfor %}
        </li>
    {% endif %}

{% endblock %}

templates/index/genre.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ genre }}{% endblock %}

{% block body %}
    <h1>{{ genre }}</h1>
    <h5>Retrouvez sur cette page tous les films et séries du genre : {{ genre }}</h5>
    <ul>
    {% for film in films %}
    <li>
        {{ film.primaryTitle }}
        <a href="{{ path('app_fiche', {'id': film.id}) }}">(voir la fiche)</a>
    </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Index Séries et Films{% endblock %}

{% block body %}

    <style>
        .desc{
            text-align: center;
        }

    </style>
    <div class="desc">
    <h1>Séries et Films</h1>
    <p>Retrouvez toutes les séries et films sur cette page.<br>
    Consulter leur fiche individuelle en cliquant sur l'hyperlien</p>
    </div>

    {% for lettre in lettres %}


        {% set films_correspondants = [] %}
        {% for film in films%}
            {% if film.primaryTitle[:1]|lower == lettre %}
                {% set films_correspondants = films_correspondants + [film] %}
            {% endif %}
        {% endfor %}


        {% if films_correspondants|length > 0 %}
            <h2>{{ lettre|upper }}</h2>
            <ul>
                {% for film in films_correspondants %}
                    <li>
                        {{ film.primaryTitle }}
                        <a href="{{ path('app_fiche', {'id': film.id}) }}">(voir la fiche)</a>
                    </li>
                {% endfor %}

            </ul>
    {% endif %}
    {% endfor %}
{% endblock %}

templates/index/indexPersonne.html.twig
{% extends 'base.html.twig' %}

{% block title %}Index{% endblock %}

{% block body %}

    <style>
        .desc{
            text-align: center;
        }

    </style>
    <div class="desc">
    <h1>Index</h1>
    <p>Retrouvez tous les acteurs, réalisateurs et stars du cinéma sur cette page.<br>
    Consulter leur fiche individuelle en cliquant sur l'hyperlien</p>
    </div>

    {% for lettre in lettres %}


        {% set acteurs_correspondants = [] %}
        {% for acteur in acteurs%}
            {% if acteur.primaryName[:1]|lower == lettre %}
                {% set acteurs_correspondants = acteurs_correspondants + [acteur] %}
            {% endif %}
        {% endfor %}


        {% if acteurs_correspondants|length > 0 %}
            <h2>{{ lettre|upper }}</h2>
            <ul>
                {% for acteur in acteurs_correspondants %}
                    <li>{{ acteur.primaryName }} {{ acteur.name }}
                        <a href="{{ path('app_fiche_personne', {'id': acteur.id}) }}">(voir la fiche)</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

    {% endfor %}
{% endblock %}